version: 2.1

parameters:
  imageName:
    type: string
    default: ""
  imageTag:
    type: string
    default: ""
  shopwareVersion:
    description: make sure a push does not trigger any workflow
    type: string
    default: ""

# -----------------------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------

workflows:

  release-image:
    when:
      and:
        - not:
            equal: [ "", << pipeline.parameters.imageName >> ]
    jobs:
      - job-build-arm64:
          name: build-arm
          imageName: << pipeline.parameters.imageName >>
          imageTag: << pipeline.parameters.imageTag >>
      # ------------------------------------------------------------------------------------
      - job-build-amd64:
          name: build-ard
          imageName: << pipeline.parameters.imageName >>
          imageTag: << pipeline.parameters.imageTag >>
      # ------------------------------------------------------------------------------------
      - job-update-manifest:
          name: update-manifest
          imageName: << pipeline.parameters.imageName >>
          imageTag: << pipeline.parameters.imageTag >>
          requires:
            - build-arm
            - build-ard

  release-shopware:
    when:
      and:
        - not:
            equal: [ "", << pipeline.parameters.shopwareVersion >> ]
    jobs:
      # ------------------------------------------------------------------------------------
      - job-build-arm64:
          name: sw-<< pipeline.parameters.shopwareVersion >>-dev-arm64
          imageName: "dev"
          imageTag: << pipeline.parameters.shopwareVersion >>
      # ------------------------------------------------------------------------------------
      - job-build-arm64:
          name: sw-<< pipeline.parameters.shopwareVersion >>-play-arm64
          imageName: "play"
          imageTag: << pipeline.parameters.shopwareVersion >>
      # ------------------------------------------------------------------------------------
      - job-build-amd64:
          name: sw-<< pipeline.parameters.shopwareVersion >>-dev-amd64
          imageName: "dev"
          imageTag: << pipeline.parameters.shopwareVersion >>
      # ------------------------------------------------------------------------------------
      - job-build-amd64:
          name: sw-<< pipeline.parameters.shopwareVersion >>-play-amd64
          imageName: "play"
          imageTag: << pipeline.parameters.shopwareVersion >>
      # ------------------------------------------------------------------------------------
      - job-update-manifest:
          name: update-manifest-dev
          imageName: "dev"
          imageTag: << pipeline.parameters.shopwareVersion >>
          requires:
            - sw-<< pipeline.parameters.shopwareVersion >>-dev-amd64
            - sw-<< pipeline.parameters.shopwareVersion >>-dev-arm64
      # ------------------------------------------------------------------------------------
      - job-update-manifest:
          name: update-manifest-play
          imageName: "play"
          imageTag: << pipeline.parameters.shopwareVersion >>
          requires:
            - sw-<< pipeline.parameters.shopwareVersion >>-play-amd64
            - sw-<< pipeline.parameters.shopwareVersion >>-play-arm64


# -----------------------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:

  job-build-arm64:
    parameters:
      imageName:
        type: string
      imageTag:
        type: string
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    resource_class: arm.medium
    steps:
      - checkout
      - cmd_install
      - cmd_image_build_push:
          imageName: <<parameters.imageName>>
          imageTag: <<parameters.imageTag>>
          imageArch: "arm64"

  job-build-amd64:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    resource_class: medium
    parameters:
      imageName:
        type: string
      imageTag:
        type: string
    steps:
      - checkout
      - cmd_install
      - cmd_image_build_push:
          imageName: << parameters.imageName >>
          imageTag: << parameters.imageTag >>
          imageArch: "amd64"

  job-update-manifest:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    resource_class: medium
    parameters:
      imageName:
        type: string
      imageTag:
        type: string
    steps:
      # ------------------------------------------------------------------------------------
      - run:
          name: Docker Hub Login
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      # ------------------------------------------------------------------------------------
      - run:
          name: Create Manifest
          command: |
            docker manifest create dockware/<< parameters.imageName >>:<< parameters.imageTag >> --amend dockware/<< parameters.imageName >>:<< parameters.imageTag >>-amd64 --amend dockware/<< parameters.imageName >>:<< parameters.imageTag >>-arm64
      # ------------------------------------------------------------------------------------
      - run:
          name: Push Manifest
          command: |
            docker manifest push dockware/<< parameters.imageName >>:<< parameters.imageTag >>


# -----------------------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------

commands:

  cmd_install:
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y php-cli php-xml unzip
      - run: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - run: php composer-setup.php
      - run: sudo mv composer.phar /usr/local/bin/composer
      # ------------------------------------------------------------------------------------
      - run: make install
      # ------------------------------------------------------------------------------------
      # ORCA generate command
      - run: make generate phar=1 -B

  cmd_image_build_push:
    parameters:
      imageName:
        type: string
      imageTag:
        type: string
      imageArch:
        type: string
    steps:
      # ------------------------------------------------------------------------------------
      - run:
          name: Verify Configuration
          command: |
            make verify image=<< parameters.imageName >> tag=<< parameters.imageTag >> -B
      # ------------------------------------------------------------------------------------
      - run:
          name: Build Image << parameters.imageName >>:<< parameters.imageTag >>
          command: |
            make build image=<< parameters.imageName >> tag=<< parameters.imageTag >> -B
      # ------------------------------------------------------------------------------------
      - run:
          name: Run SVRUnit Tests
          command: |
            make test image=<< parameters.imageName >> tag=<< parameters.imageTag >> -B
      - store_test_results:
          path: .reports
        # ------------------------------------------------------------------------------------
      - run:
          name: Run Cypress Tests
          environment:
            IMG: << parameters.imageName >>
            TAG: << parameters.imageTag >>
          command: |
            docker run --rm -p 80:80 --name shop -d dockware/$IMG:$TAG
            sleep 30
            docker logs shop
            cd tests/cypress && make install -B
            echo "Running Cypress tests for: $IMG:$TAG"
            if [[ $IMG == "flex" ]]; then
              cd tests/cypress && make run-flex url=http://localhost
            elif [[ $IMG == "essentials" ]]; then
              cd tests/cypress && make run-essentials url=http://localhost
            elif [[ $IMG == "play" && $TAG == "latest" ]]; then
              cd tests/cypress && make run6 url=http://localhost shopware=6.4.20.0
            elif [[ $IMG == "dev" && $TAG == "latest" ]]; then
              cd tests/cypress && make run6 url=http://localhost shopware=6.4.20.0
            elif [[ $IMG == "dev" && $TAG == "6.5.0.0-rc1" ]]; then
              cd tests/cypress && make run6 url=http://localhost shopware=6.5.0.0
            elif [[ $IMG == "6."* ]]; then
              cd tests/cypress && make run6 url=http://localhost shopware=$TAG
            elif [[ $IMG == "5."* ]]; then
              cd tests/cypress && make run5 url=http://localhost shopware=$TAG
            else
              echo "NO CYPRESS CONFIGURATION FOUND FOR IMAGE"
              exit 1
            fi
      # ------------------------------------------------------------------------------------
      - run:
          name: Docker Hub Login
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Tag Image for ARCH
          command: |
            docker tag dockware/<< parameters.imageName >>:<< parameters.imageTag >> dockware/<< parameters.imageName >>:<< parameters.imageTag >>-<< parameters.imageArch >>
      - run:
          name: Push Image
          command: |
            docker push dockware/<< parameters.imageName >>:<< parameters.imageTag >>-<< parameters.imageArch >>