name: Release dockware/contribute:*

#only manuelly
on:
  workflow_dispatch:

jobs:
  
    build-contribute-latest:
      name: Release contribute:latest
      runs-on: ubuntu-latest
      steps:
        - name: Clone Code
          uses: actions/checkout@v2
    
        - name: Install Dependencies
          run: make install
    
        - name: ORCA Generate
          run: make generate
    
        - name: Build
          run: make build image=contribute tag=latest -B
    
        - name: Tests
          run: make test image=contribute tag=latest -B
          
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
        - name: Push to Docker Hub
          run: php ./build/push_dockerhub.php contribute latest