name: Release Image

#only manuelly
on:
  workflow_dispatch:
    inputs:
      imageName:
        description: 'Image Name'
        required: true
      tagName:
        description: 'Tag Name'
        required: true


jobs:
  install:
    name: Generate the dockerfiles
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: make install

      - name: ORCA Generate
        run: make generate

      - name: Build
        run: make build image=${{ github.event.inputs.imageName }} tag=${{ github.event.inputs.tagName }} -B

      - name: Tests
        run: make test image=${{ github.event.inputs.imageName }} tag=${{ github.event.inputs.tagName }} -B

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to Docker Hub
        run: docker push dockware/${{ github.event.inputs.imageName }}:${{ github.event.inputs.tagName }}
