name: Release dockware/flex:*

#only manually
on:
  workflow_dispatch:

jobs:
  
    build-flex-latest:
      name: Release flex:latest
      runs-on: ubuntu-latest
      steps:
        - name: Clone Code
          uses: actions/checkout@v2
    
        - name: Install Dependencies
          run: make install
    
        - name: ORCA Generate
          run: make generate
    
        - name: Build
          run: make build image=flex tag=latest -B
    
        - name: SVRUnit Tests
          run: make test image=flex tag=latest -B
          
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
        - name: Push to Docker Hub
          run: docker push dockware/flex:latest