name: Release dockware/contribute:*

#only manuelly
on:
  workflow_dispatch:

jobs:
  
    build-contribute-latest:
      name: build dockware/contribute:latest
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: install
          run: make install
    
        - name: Generate docker files
          run: make generate
    
        - name: Generate Build commands for dev image
          run: php ./build/build.php contribute latest
    
        - name: Build the contribute latest image
          run: make build image=contribute tag=latest
    
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
        - name: Push Images to dockerhub
          run: php ./build/push_dockerhub.php contribute latest