name: Build dockware images

on: push

jobs:
  generate-images:
    name: Generate the dockerfiles
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install
        run: make install

      - name: Generate docker files
        run: make generate

      - name: Build flex image
        run: make build image=flex tag=latest

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dockware/flex-test
          tag_with_ref: true