name: Release Shopware Version

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag Name'
        required: true


jobs:

  play:
    name: Build Shopware ${{ matrix.image }}:${{ github.event.inputs.tagName }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ 'play', 'dev' ]
    steps:

      - name: Clone Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: make install

      - name: ORCA Generate
        run: make generate -B

      - name: Build Image
        run: make build image=${{ matrix.image }} tag=${{ github.event.inputs.tagName }} -B

      - name: Run SVRUnit Tests
        run: make test image=${{ matrix.image }} tag=${{ github.event.inputs.tagName }} -B

      - name: Store SVRUnit Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: svrunit_report
          retention-days: 3
          path: |
            .reports

      - name: Start Container
        run: |
          docker run --rm -p 80:80 --name shop -d dockware/${{ matrix.image }}:${{ github.event.inputs.tagName }}
          sleep 30
          docker logs shop

      - name: Install Cypress
        run: cd tests/cypress && make install -B

      - name: Run Cypress Tests
        run: |
          if [[ $DW_IMAGE == flex ]]; then
            cd tests/cypress && make run-flex url=http://localhost
          fi
          if [[ $DW_IMAGE == essentials ]]; then
             cd tests/cypress && make run-essentials url=http://localhost
          fi
          if [[ $DW_IMAGE == play && $SW_VERSION == latest ]]; then
             cd tests/cypress && make run6 url=http://localhost
          fi
          if [[ $DW_IMAGE == dev && $SW_VERSION == latest ]]; then
             cd tests/cypress && make run6 url=http://localhost
          fi
          if [[ $SW_VERSION == 6.* ]]; then
             cd tests/cypress && make run6 url=http://localhost
          fi
          if [[ $SW_VERSION == 5.* ]]; then
             cd tests/cypress && make run5 url=http://localhost
          fi
        env:
          DW_IMAGE: ${{ matrix.image }}
          SW_VERSION: ${{ github.event.inputs.tagName }}

      - name: Store Cypress Results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress_results
          retention-days: 3
          path: |
            Tests/Cypress/cypress/videos
            Tests/Cypress/cypress/screenshots

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to Docker Hub
        run: docker push dockware/${{ matrix.image }}:${{ github.event.inputs.tagName }}